"""
plots/mfa_escalation_breakdown.py

Reports real trust-driven step-up MFA escalation counts from AuditLog,
generated by require_stepup_mfa_if_low_trust() in ztna/views.py (wired into
create_file_view, edit_file_view, share_file_view, fire_cmds_view -- the
four sensitive actions in Table IX). This is a genuinely separate signal
from ZTNARequest.status (see enforcement_outcome_breakdown.py): it counts
MFA-escalation events specifically, not page-level access outcomes.

Run with:
    python plots/mfa_escalation_breakdown.py
"""

import os
import re
import sys
import django
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ztna_proj.settings")
django.setup()

from django.db.models import Count
from siem.models import AuditLog

required = AuditLog.objects.filter(action__startswith="Step-up MFA required for")
by_action = dict(
    required.values_list("action").annotate(n=Count("id")).order_by("-n")
)
success = AuditLog.objects.filter(action="Step-up MFA Success").count()
failed = AuditLog.objects.filter(action="Step-up MFA Failed").count()

print("=== Step-up MFA Escalation Events (real, from AuditLog) ===")
print(f"Total escalation triggers: {required.count()}")
for action, n in by_action.items():
    label = action.replace("Step-up MFA required for ", "")
    print(f"  -- triggered by {label:<28}: {n}")
print(f"Step-up MFA Success: {success}")
print(f"Step-up MFA Failed : {failed}")

# ── Breakdown by trigger REASON (device_score check added after the initial
# wiring -- see require_stepup_mfa_if_low_trust in ztna/views.py). Events
# logged before that fix has no "(...)" suffix at all -- bucketed as legacy.
REASON_RE = re.compile(r"\(([^)]+)\)$")
reason_counts = {"low behavioral trust": 0, "unrecognized device": 0,
                  "low behavioral trust and unrecognized device": 0,
                  "legacy / unlabeled (pre-device-check)": 0}
for action, n in by_action.items():
    m = REASON_RE.search(action)
    key = m.group(1) if m else "legacy / unlabeled (pre-device-check)"
    reason_counts[key] = reason_counts.get(key, 0) + n

print("\n=== Breakdown by trigger reason ===")
for reason, n in reason_counts.items():
    print(f"  {reason:<48}: {n}")

counts = {"Triggered": required.count(), "Success": success, "Failed": failed}
plt.figure(figsize=(5, 4))
bars = plt.bar(list(counts.keys()), list(counts.values()),
                color=["#DD8452", "#55A868", "#C44E52"])
for bar, val in zip(bars, counts.values()):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.1,
              str(val), ha="center", va="bottom", fontsize=10)
plt.ylabel("Number of Events")
plt.title("Step-Up MFA Escalation Outcomes")
plt.tight_layout()
plt.savefig(BASE_DIR / "mfa_escalation_breakdown.png", dpi=300)
plt.close()
print(f"\n[OK] Saved mfa_escalation_breakdown.png")

# ── Second figure: trigger reason breakdown ──
labels = [k for k, v in reason_counts.items() if v > 0]
values = [reason_counts[k] for k in labels]
short_labels = [
    l.replace("legacy / unlabeled (pre-device-check)", "Legacy\n(pre-fix)")
     .replace("low behavioral trust and unrecognized device", "Trust +\nDevice")
     .replace("low behavioral trust", "Low Trust\nOnly")
     .replace("unrecognized device", "Unrecognized\nDevice Only")
    for l in labels
]

plt.figure(figsize=(6, 4))
bars = plt.bar(short_labels, values, color=["#8C8C8C", "#4C72B0", "#DD8452", "#937860"][: len(values)])
for bar, val in zip(bars, values):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.1,
              str(val), ha="center", va="bottom", fontsize=10)
plt.ylabel("Number of Escalation Triggers")
plt.title("Step-Up MFA Triggers by Reason")
plt.tight_layout()
plt.savefig(BASE_DIR / "mfa_escalation_by_reason.png", dpi=300)
plt.close()
print("[OK] Saved mfa_escalation_by_reason.png")

if required.count() == 0:
    print(
        "\n[NOTE] Zero escalation events recorded. This gate was only wired "
        "into the sensitive-action views in this revision -- prior usage "
        "never had a live trigger for it. Interact with the app for a few "
        "sessions (or let behavioral trust drop below 0.60 via normal "
        "MFA-failure/bad-password events, then attempt a sensitive action) "
        "before regenerating this for the final submission."
    )
