# Generated by Django 5.2.7 on 2025-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='auto_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='risk_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='policyrule',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='policyrule',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
