# Generated by Django 5.2.7 on 2025-11-26 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_policy_auto_apply_policy_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='auto_apply',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='policyrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='policyrule',
            name='tag',
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
