# Generated by Django 5.2.7 on 2025-12-08 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0001_initial'),
        ('policy', '0003_remove_policy_auto_apply_remove_policy_is_mandatory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('raw', models.TextField()),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp.userprofile')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
