# Generated by Django 5.2.7 on 2026-07-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_devicefingerprintrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceRecord',
        ),
    ]
