# Generated by Django 5.2.7 on 2025-11-23 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appsrv', '0001_initial'),
        ('idp', '0001_initial'),
        ('policy', '0001_initial'),
        ('trustbroker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_mode', models.CharField(choices=[('open', 'Open Access'), ('strict', 'Strict Access'), ('expire', 'Temporary Access')], default='open', max_length=10)),
                ('allowed_users', models.TextField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZTNARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('decision_reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsrv.applicationresource')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.policy')),
                ('trust_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trustbroker.trustscore')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp.userprofile')),
            ],
        ),
    ]
