# Generated by Django 5.2.7 on 2025-11-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
