# Generated by Django 5.2.7 on 2025-12-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0003_devicefingerprintrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceFingerprintRecord',
        ),
    ]
