# Generated by Django 5.2.7 on 2026-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0004_delete_devicefingerprintrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ztnarequest',
            name='policy_rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
