# Generated by Django 5.2.7 on 2025-11-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationresource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationresource',
            name='owner',
        ),
        migrations.AlterField(
            model_name='applicationresource',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
