# Generated by Django 5.2.7 on 2026-01-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
