# Generated by Django 5.2.7 on 2026-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0002_auditlog_latency_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='policy_rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
