# Generated by Django 5.2.7 on 2026-01-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0003_auditlog_policy_rule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('BLOCKED', 'BLOCKED'), ('ADMIN_UNBLOCK', 'ADMIN_UNBLOCK')], default='SUCCESS', max_length=50),
        ),
    ]
