# Generated by Django 5.2.7 on 2026-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0004_alter_auditlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('BLOCKED', 'BLOCKED'), ('ADMIN_UNBLOCK', 'ADMIN_UNBLOCK'), ('REQUIRE_MFA', 'REQUIRE_MFA')], default='SUCCESS', max_length=50),
        ),
    ]
