# Generated by Django 5.2.7 on 2025-11-23 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bad_password', 'Bad Password Attempt'), ('mfa_fail', 'MFA Failure'), ('blocked', 'Blocked by Policy/Admin Restriction'), ('link_fail', 'Unauthorized Link Access'), ('login_success', 'Successful Login'), ('trust_recovery_hourly', 'Hourly Trust Recovery'), ('trust_recovery_safe', 'Safe Action Trust Recovery'), ('trust_recovery_mfa', 'MFA Trust Recovery')], max_length=50)),
                ('delta', models.FloatField(default=0.0)),
                ('old_score', models.FloatField(default=1.0)),
                ('new_score', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_trust', models.FloatField(default=1.0)),
                ('last_recovery', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='idp.userprofile')),
            ],
        ),
    ]
